
name: uploadToS3
on:
  push:
    branches: [ "awsDev" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
          npm ci
          npm run build
          touch out/.nojekyll
          # configure the build here
    - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: awsDev
        folder: out
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete  --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'sa-east-1'   # optional: defaults to us-east-1
